# Generated by Django 5.1.8 on 2025-08-29 08:15

import apps.radio_program.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioprogram',
            name='audio_file',
            field=models.FileField(upload_to='audio/', validators=[apps.radio_program.models.validate_audio_file]),
        ),
    ]
