# Generated by Django 5.1.8 on 2025-11-28 04:49

import apps.radio_program.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_program', '0002_alter_radioprogram_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioprogram',
            name='type',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(100, 'Tuesday Program'), (200, 'Together for Humanity')], choices_enum=apps.radio_program.models.RadioProgramTypeEnum, default=100),
        ),
    ]
