# Generated by Django 5.1.8 on 2025-12-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='Is Notice'),
        ),
    ]
