# Generated by Django 5.1.8 on 2025-08-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='procurement/', verbose_name='Procurement file'),
        ),
    ]
