# Generated by Django 5.1.8 on 2025-08-21 04:53

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', markdownx.models.MarkdownxField()),
                ('file', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
