# Generated by Django 5.1.8 on 2025-08-22 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('strategic', '0002_strategicdirectives_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='directive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='strategic.strategicdirectives'),
        ),
    ]
