# Generated by Django 5.1.8 on 2025-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_directive'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
