# Generated by Django 5.1.8 on 2025-09-02 08:32

import apps.resources.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Report'), (20, 'Policy And Guidelines')], choices_enum=apps.resources.models.ResourcesType, default=10),
        ),
    ]
