# Generated by Django 5.1.8 on 2025-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_highlight_options_highlight_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='highlight',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
