# Generated by Django 5.1.8 on 2026-08-27 08:43

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_highlight_expiry_date_highlight_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='description',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
