# Generated by Django 5.1.8 on 2026-08-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_highlight_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('stat', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_stats', to='home.highlight')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('highlight', 'order'), name='unique_key_stat_order_per_highlight')],
            },
        ),
    ]
