# Generated by Django 5.1.8 on 2026-08-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_keystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='highlights/files/')),
                ('order', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='home.highlight')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('highlight', 'order'), name='unique_highlight_file_order_per_highlight')],
            },
        ),
    ]
