# Generated by Django 5.1.8 on 2026-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_highlightfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='show_in_popup',
            field=models.BooleanField(default=False),
        ),
    ]
