# Generated by Django 5.1.8 on 2025-11-25 14:00

import apps.common.models
import django.db.models.deletion
import django_choices_field.fields
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('strategic', '0002_strategicdirectives_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=232, verbose_name='Title')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('content', mdeditor.fields.MDTextField(verbose_name='Content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Cover Image')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(50, 'Draft'), (60, 'Published'), (70, 'Archived')], choices_enum=apps.common.models.StatusEnum, default=50)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='Department')),
                ('directive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategic.strategicdirectives', verbose_name='Strategic Directive')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
