# Generated by Django 5.1.8 on 2025-08-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('department', '0001_initial'),
        ('strategic', '0002_strategicdirectives_cover_image'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='directive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategic.strategicdirectives', verbose_name='Strategic Directive'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.work', verbose_name='Work'),
        ),
    ]
