# Generated by Django 5.1.8 on 2025-09-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_department_alter_blog_directive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='work',
        ),
    ]
