# Generated by Django 5.1.8 on 2025-08-22 04:11

import apps.partner.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='scope',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Local'), (2, 'Global')], choices_enum=apps.partner.models.PartnerScopeEnum),
        ),
    ]
