# Generated by Django 5.1.8 on 2026-09-24 09:24

import apps.cec_member.models
import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CecMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('member_type', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Office Bearer'), (2, 'Member'), (3, 'Staff')], choices_enum=apps.cec_member.models.CecMemberTypeEnum, default=2)),
                ('designation', models.CharField(blank=True, help_text='Shown as the heading for office bearers and staff, e.g. Chairperson.', max_length=255, null=True, verbose_name='Designation')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cec-member/', verbose_name='Photo')),
                ('order_index', models.IntegerField(default=0, verbose_name='Order index')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive members are kept in the CMS but hidden from the website.', verbose_name='Is active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CEC member',
                'verbose_name_plural': 'CEC members',
                'db_table': 'cec_member',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
