# Generated by Django 5.1.8 on 2025-08-20 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField()),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person Name')),
                ('contact_person_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Contact Person Email')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('strategic_directive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strategic.strategicdirectives', verbose_name='Strategic Directive')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
