# Generated by Django 5.1.8 on 2025-08-20 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('strategic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='strategic_directive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategic.strategicdirectives', verbose_name='Strategic Directive'),
        ),
    ]
