# Generated by Django 5.1.8 on 2026-02-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_end_date_remove_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(default="", upload_to='project/cover_image'),
            preserve_default=False,
        ),
    ]
