# Generated by Django 5.1.8 on 2025-08-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicdirectives',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='strategic_directives/cover_images', verbose_name='Cover Image'),
        ),
    ]
