# Generated by Django 5.1.8 on 2025-09-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0002_strategicdirectives_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicdirectives',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AlterField(
            model_name='strategicdirectives',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='strategicdirectives',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
