# Generated by Django 5.1.8 on 2025-12-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0002_strategicdirectives_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategicdirectives',
            name='contact_person_email',
        ),
        migrations.RemoveField(
            model_name='strategicdirectives',
            name='contact_person_name',
        ),
    ]
