apiVersion: v2
name: nrcs-backend-helm
description: "Helm Chart to deploy the NRCS backend"
type: application
version: 0.1.0-SET-BY-CICD
sources:
  - https://github.com/NRCS-NRCS/nrcs-backend
dependencies:
  - name: banjo-helm
    alias: app
    version: 0.4.1
    repository: oci://ghcr.io/toggle-corp
