apiVersion: v2
name: nrcs-website-backend
description: "Helm chart for NRCs website backend"
type: application
version: 0.1.0
appVersion: "1.16.0"
sources:
  - https://github.com/toggle-corp/nrcs-backend


dependencies:
  - name: django-app
    alias: app
    version: 0.1.2
    repository: "oci://ghcr.io/toggle-corp/charts"
