app:
  environment: PROD
  appTypeEnvName: "APP_TYPE"

  # Global Image
  image:
    name: ghcr.io/stories-of-nrcs/nrcs-server-dev
    tag: feat-add-aws-config.c5acaf15
    imagePullPolicy: Always
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    host: test-nrcs-api.k8s.dev.togglecorp.com



  postgresql:
    enabled: true
    fullnameOverride: "nrcs-postgresql"
    architecture: standalone
    auth:
      postgresPassword: "2Ip9-+2%yf`d[hs+nbd1"
      username: "nrcs"
      password: "nrcs"
      database: "nrcs"
    primary:
      persistence:
        enabled: "true"
        storageClass: "local-path"
        size: 4Gi
  api:
    enabled: true
    replicaCount: 1
    containerPort: 80
    command: ["gunicorn", "nrcs.wsgi:application", "--timeout=40", "--bind", "0.0.0.0:80"]
    resources:
      requests:
        cpu: "2"
        memory: 0.5Gi
      limits:
        cpu: "4"
        memory: 1Gi



  minio:
    enabled: true
    disableWebUI: true
    mode: standalone
    fullnameOverride: nrcs-minio
    global:
      defaultStorageClass:
    apiIngress:
      enabled: true
      ingressClassName:
      hostname: nrcs.api.minio.k8s.dev.togglecorp.com
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    auth:
      forceNewKeys: true
      rootUser: nrcs

      rootPassword: testroot
    persistence:
      enabled: true
      size: 1Gi
    defaultBuckets: nrcs-static,nrcs-media
    provisioning:
      enabled: true
      resourcesPreset: "nano"
      cleanupAfterFinished:
        enabled: true
      extraCommands:
        - "mc anonymous set download provisioning/nrcs-static"
        - "mc anonymous set download provisioning/nrcs-media"

  argoHook:
    enabled: false
    resources:
      requests:
        cpu: "0.1"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    hooks:
      # NOTE: Make sure keys are lowercase
      db-migrate:
        enabled: true
        hook: PostSync
        preserveHistory: true
        command: ["/bin/bash", "-c"]
        args:
          - "./manage.py wait_for_resources --db && ./manage.py migrate"
      collect-static:
        enabled: true
        hook: PostSync
        command: ["/bin/bash", "-c"]
        args:
          - "./manage.py wait_for_resources --minio && ./manage.py collectstatic --noinput"

   # NOTE: Check main/settings.py for all available options
  env:
    AWS_S3_BUCKET_ENABLE: "true"
    DEBUG: "false"
    APP_ENVIRONMENT: "{{ $.Values.environment }}"
    TIME_ZONE: "Asia/Kathmandu"
    LANGUAGE_CODE: "en"
    AWS_S3_ENDPOINT_URL: "https://{{ $.Values.minio.apiIngress.hostname }}/"

    # App Domain
    APP_TYPE: "WEB"
    APP_DOMAIN: "https://nrcs-api.k8s.dev.togglecorp.com"
    ADDITIONAL_ALLOWED_HOSTS: "https://nrcs-api.k8s.dev.togglecorp.com"
    FRONTEND_DOMAIN: "https://frontend.example.com"
    SESSION_COOKIE_DOMAIN: ".k8s.dev.togglecorp.com"
    CSRF_COOKIE_DOMAIN: ".k8s.dev.togglecorp.com"
    ADDITIONAL_TRUSTED_ORIGINS: "https://nrcs-api.k8s.dev.togglecorp.com"


  secrets:
    DJANGO_SECRET_KEY: "thoh-2i##o2j^6--_sg-oq!j9ohqipx3_a-c2+"
    # Postgres
    DB_NAME: "{{ $.Values.postgresql.auth.database }}"
    DB_USER: "postgres"
    DB_PWD: "{{ $.Values.postgresql.auth.postgresPassword }}"
    DB_HOST: "{{ include \"postgresql.v1.primary.fullname\" $.Subcharts.postgresql }}"
    DB_PORT: "{{ include \"postgresql.v1.service.port\" $.Subcharts.postgresql }}"
    AWS_S3_ACCESS_KEY_ID: "{{ required \".app.minio.auth.rootUser\" $.Values.minio.auth.rootUser }}"
    AWS_S3_SECRET_ACCESS_KEY: "{{ required \".app.minio.auth.rootPassword\" $.Values.minio.auth.rootPassword }}"
    AWS_S3_REGION: "us-east-1"
    AWS_S3_MEDIA_BUCKET_NAME: "nrcs-media"
    AWS_S3_STATIC_BUCKET_NAME: "nrcs-static"
